SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[Client]') AND TYPE IN (N'U')) 
BEGIN

    CREATE TABLE [dbo].Client(
        [Id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
        [Name] [varchar](100) NOT NULL,
        [Email] [VARCHAR] NULL ,
		[Contact] [VARCHAR] NULL
		 )
	
END
GO